export const dom = {};

export function cacheDom() {
    Object.assign(dom, {
        splashScreen: document.getElementById('splash-screen'),
        featureShowcase: document.getElementById('feature-showcase-container'),
        startAppBtn: document.getElementById('start-app-btn'),
        screens: document.querySelectorAll('.screen'),
        welcomeScreen: document.getElementById('welcome-screen'),
        startSetupWizardBtn: document.getElementById('start-setup-wizard-btn'),
        loadFromFileBtn: document.getElementById('load-from-file-btn'),
        setupScreen: document.getElementById('setup-screen'),
        mainScreen: document.getElementById('main-screen'),
        recipeScreen: document.getElementById('recipe-screen'),
        
        // Wizard
        setupWizard: document.getElementById('setup-wizard'),
        wizardSteps: document.querySelectorAll('.wizard-step'),
        wizardNav: document.getElementById('wizard-nav'),
        wizardBackBtn: document.getElementById('wizard-back-btn'),
        wizardNextBtn: document.getElementById('wizard-next-btn'),
        wizardStepCounter: document.getElementById('wizard-step-counter'),
        apiKeyInput: document.getElementById('api-key-input'),
        apiKeyHelpLink: document.getElementById('api-key-help-link'),
        wizardFamilyContainer: document.getElementById('wizard-family-members-container'),
        wizardAddMemberBtn: document.getElementById('wizard-add-family-member-btn'),
        wizardDuration: document.getElementById('wizard-menu-duration'),
        wizardBudget: document.getElementById('wizard-total-budget'),
        wizardPreferences: document.getElementById('wizard-preferences'),
        wizardCuisine: document.getElementById('wizard-cuisine'),
        wizardDifficulty: document.getElementById('wizard-difficulty'),

        generationProgress: document.getElementById('generation-progress'),
        progressBar: document.getElementById('progress-bar'),
        progressStatus: document.getElementById('progress-status'),
        progressDetails: document.getElementById('progress-details'),
        finishSetupBtn: document.getElementById('finish-setup-btn'),
        
        bottomNav: document.querySelector('.bottom-nav'),
        mainContents: document.querySelectorAll('.main-content'),
        mainHeaderTitle: document.getElementById('main-header-title'),
        
        dayScroller: document.getElementById('day-scroller-container'),
        shoppingListContainer: document.getElementById('shopping-list-container'),
        shoppingProgressText: document.getElementById('shopping-progress-text'),
        shoppingProgress: document.getElementById('shopping-progress'),
        shoppingListTotal: document.getElementById('shopping-list-total'),

        backToMenuBtn: document.getElementById('back-to-menu-btn'),
        recipeTitle: document.getElementById('recipe-title'),
        stepIndicator: document.getElementById('step-indicator'),
        stepImageContainer: document.querySelector('.recipe-image-container'),
        stepImage: document.getElementById('step-image'),
        stepImagePlaceholder: document.getElementById('recipe-image-placeholder'),
        stepImageLoader: document.getElementById('recipe-image-loader'),
        generateImageBtn: document.getElementById('generate-image-btn'),
        stepDescription: document.getElementById('step-description'),
        timerSection: document.getElementById('timer-section'),
        timerDisplay: document.getElementById('timer-display'),
        startTimerBtn: document.getElementById('start-timer-btn'),
        pauseTimerBtn: document.getElementById('pause-timer-btn'),
        resetTimerBtn: document.getElementById('reset-timer-btn'),
        stepIngredientsList: document.getElementById('step-ingredients'),
        stepIngredientsTitle: document.getElementById('step-ingredients-title'),
        prevStepBtn: document.getElementById('prev-step-btn'),
        nextStepBtn: document.getElementById('next-step-btn'),
        
        budget: {
            pieProducts: document.getElementById('pie-products'),
            spentTotal: document.getElementById('budget-spent-total'),
            total: document.getElementById('budget-total'),
            remaining: document.getElementById('budget-remaining'),
        },

        settings: {
            duration: document.getElementById('settings-menu-duration'),
            budget: document.getElementById('settings-total-budget'),
            preferences: document.getElementById('settings-preferences'),
            cuisine: document.getElementById('settings-cuisine'),
            difficulty: document.getElementById('settings-difficulty'),
            saveBtn: document.getElementById('save-settings-btn'),
            familyContainer: document.getElementById('family-members-container'),
            addMemberBtn: document.getElementById('add-family-member-btn'),
            regenerateAllBtn: document.getElementById('regenerate-all-btn'),
            apiKeyInput: document.getElementById('settings-api-key'),
            saveApiKeyBtn: document.getElementById('save-api-key-btn'),
            runWizardBtn: document.getElementById('run-wizard-btn'),
            appVersionInfo: document.getElementById('app-version-info'),
            showChangelogBtn: document.getElementById('show-changelog-btn'),
        },
        exportBtn: document.getElementById('export-btn'),
        importBtn: document.getElementById('import-btn'),
        importFileInput: document.getElementById('import-file-input'),

        devConsole: document.getElementById('dev-console'),
        logOutput: document.getElementById('log-output'),
        commandInput: document.getElementById('command-input'),

        notification: document.getElementById('notification'),
        notificationSound: document.getElementById('notification-sound'),

        modalOverlay: document.getElementById('modal-overlay'),
        modalTitle: document.getElementById('modal-title'),
        modalBody: document.getElementById('modal-body'),
        modalButtons: document.getElementById('modal-buttons'),
    });
}
